# Generated by Django 4.0.1 on 2022-01-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название ингридиента'),
        ),
    ]
