# Generated by Django 4.0.1 on 2022-01-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ingredients_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='steret',
            new_name='street',
        ),
    ]
