# Generated by Django 4.0.1 on 2022-01-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_steret_user_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
