# Generated by Django 4.0.1 on 2022-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_restaurants_pizza_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_house',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название улицы'),
        ),
    ]
